## Configuration for the from Snakemake workflow.

# sample name, pointing to STARsolo output directory (same as the ""--outFileNamePrefix" input for STAR)
#TODO: add sample_sheet read-ins as an option for passing sample lists
Samples:
  C2Cnuc_yPAP1:
  C2Cnuc_ctrl1:

# .fasta (genome sequence) and .gtf (gene annotations) files used to build STAR reference
## Mouse
GENOME_FASTA: /workdir/dwm269/genomes/mm39_all/GENCODE_M28/GRCm39.genome.fa
GENES_GTF: /workdir/dwm269/genomes/mm39_all/GENCODE_M28/gencode.vM28.chr_patch_hapl_scaff.annotation.gtf

## Human
# GENOME_FASTA: "/workdir/dwm269/genomes/GRCh38_all/GENCODE_GRCh38p13/GRCh38.p13.genome.fa"
# GENES_GTF: "/workdir/dwm269/genomes/GRCh38_all/GENCODE_GRCh38p13/gencode.v38.chr_patch_hapl_scaff.annotation.gtf"

# directory where STARsolo outputs are stored - be sure to use an absolute path (starting with root)
DATADIR: /workdir/dwm269/totalRNA/data/STARsolo/GRCm39_GENCODEM28_Chromium
# DATADIR: /workdir/dwm269/ma_ipsc/data/STARsolo/GRCh38p13

# directory for temporary files
TMPDIR: /workdir/dwm269/totalRNA/tmp
# ./

########################################################################################################
# Executables - file paths
########################################################################################################
PICARD: /home/dwm269/miniconda3/envs/scTAR1.2/share/picard-2.18.29-0/picard.jar
DROPSEQ: /home/dwm269/miniconda3/envs/scTAR1.2/share/dropseq_tools-2.4.0-1
GTFTOGENEPRED: /home/dwm269/miniconda3/envs/scTAR1.2/bin/gtfToGenePred # used to convert gtf to reFflat format, not needed if annotation is in reFflat
BLASTDB: /shared_data/genome_db/BLAST_NCBI # path to where the nt BLAST database is stored

CORES: 12 # how many cores to give for each process (snakemake automatically parallelizes process using "snakemake -j {numTotalCores}")

MERGEBP: 500 #default 500 (Note- window size across genome is 50bp)
THRESH: 10000000 #default 10000000
